using Monthoya.Core.Entities;
using Monthoya.Core.Services;

namespace Monthoya.Data.RentalManagement;

public sealed partial class RentalManagementService
{
    private static CreateImovelRequest ToImovelRequest(Imovel imovel) =>
        new(
            ProprietarioId: imovel.ProprietarioId,
            Rua: imovel.Rua,
            Numero: imovel.Numero,
            Bairro: imovel.Bairro,
            Cidade: imovel.Cidade,
            Estado: imovel.Estado,
            ValorAluguel: imovel.ValorAluguel,
            Finalidade: imovel.Finalidade,
            Observacoes: imovel.Observacoes,
            Complemento: imovel.Complemento,
            Cep: imovel.Cep,
            SaneparMatricula: imovel.SaneparMatricula,
            CopelMatricula: imovel.CopelMatricula,
            IptuInscricaoImobiliaria: imovel.IptuInscricaoImobiliaria,
            IptuCadastroImovel: imovel.IptuCadastroImovel,
            ColetaLixo: imovel.ColetaLixo,
            TipoImovel: imovel.TipoImovel,
            Descricao: imovel.Descricao,
            ValorVenda: imovel.ValorVenda,
            Latitude: imovel.Latitude,
            Longitude: imovel.Longitude,
            Status: imovel.Status,
            ValorCondominio: imovel.ValorCondominio,
            ValorIptu: imovel.ValorIptu,
            Quartos: imovel.Quartos,
            Suites: imovel.Suites,
            Banheiros: imovel.Banheiros,
            VagasGaragem: imovel.VagasGaragem,
            Salas: imovel.Salas,
            Cozinhas: imovel.Cozinhas,
            Copas: imovel.Copas,
            Despensas: imovel.Despensas,
            Lavanderias: imovel.Lavanderias,
            AreasServico: imovel.AreasServico,
            Lavabos: imovel.Lavabos,
            Sacadas: imovel.Sacadas,
            Churrasqueiras: imovel.Churrasqueiras,
            Piscinas: imovel.Piscinas,
            Quintais: imovel.Quintais,
            HallsEntrada: imovel.HallsEntrada,
            Estendais: imovel.Estendais,
            AreaConstruida: imovel.AreaConstruida,
            AreaTerreno: imovel.AreaTerreno,
            Mobiliado: imovel.Mobiliado,
            AceitaPets: imovel.AceitaPets,
            DescricaoInterna: imovel.DescricaoInterna,
            DescricaoPublica: imovel.DescricaoPublica,
            PublicarNoSite: imovel.PublicarNoSite,
            PublicarNoApp: imovel.PublicarNoApp,
            Destaque: imovel.Destaque,
            MostrarEnderecoCompletoPublicamente: imovel.MostrarEnderecoCompletoPublicamente,
            ModoExibicaoEnderecoPublico: imovel.ModoExibicaoEnderecoPublico,
            ChavePosse: imovel.ChavePosse,
            ChaveCodigo: imovel.ChaveCodigo,
            ChaveQuemTem: imovel.ChaveQuemTem,
            ChaveTelefone: FormatPhoneForDisplay(imovel.ChaveTelefone),
            ChaveContatoNome: imovel.ChaveContatoNome,
            ChaveContatoDocumento: imovel.ChaveContatoDocumento,
            ChaveLocalRetirada: imovel.ChaveLocalRetirada,
            ChaveMelhorHorario: imovel.ChaveMelhorHorario,
            ChaveAutorizacaoNecessaria: imovel.ChaveAutorizacaoNecessaria,
            ChaveObservacoes: imovel.ChaveObservacoes);
}
