using Monthoya.Core.Entities;
using Monthoya.Core.Services;

namespace Monthoya.Data.RentalManagement;

public sealed partial class RentalManagementService
{
    private static CreatePessoaRequest ToPessoaRequest(Pessoa pessoa)
    {
        if (pessoa.TipoPessoa == TipoPessoa.Fisica && pessoa.PessoaFisica is not null)
        {
            var fisica = pessoa.PessoaFisica;
            return new CreatePessoaRequest(
                TipoPessoa: pessoa.TipoPessoa,
                NomeDisplay: pessoa.NomeDisplay,
                Telefone: FormatPhoneForDisplay(fisica.Telefone ?? pessoa.Telefone),
                Email: fisica.Email ?? pessoa.Email,
                Documento: FormatCpf(fisica.Cpf),
                Observacoes: pessoa.Observacoes,
                Rua: fisica.Rua,
                Numero: fisica.Numero,
                Complemento: fisica.Complemento,
                Bairro: fisica.Bairro,
                Cidade: fisica.Cidade,
                Estado: fisica.Estado,
                Cep: FormatCepForDisplay(fisica.Cep),
                EstadoCivil: fisica.EstadoCivil,
                PossuiTrabalho: fisica.PossuiTrabalho,
                PossuiPet: fisica.PossuiPet,
                PetQual: fisica.PetQual,
                Nacionalidade: fisica.Nacionalidade,
                DataNascimento: fisica.DataNascimento,
                Rg: FormatRgForDisplay(fisica.Rg),
                Profissao: fisica.Profissao,
                OndeTrabalha: fisica.OndeTrabalha,
                EnderecoTrabalho: fisica.EnderecoTrabalho,
                NomeEmpresaTrabalho: fisica.NomeEmpresaTrabalho,
                CnpjEmpresaTrabalho: FormatCnpj(fisica.CnpjEmpresaTrabalho),
                TelefoneEmpresaTrabalho: FormatPhoneForDisplay(fisica.TelefoneEmpresaTrabalho),
                EmailEmpresaTrabalho: fisica.EmailEmpresaTrabalho,
                CargoTrabalho: fisica.CargoTrabalho,
                RendaTrabalho: fisica.RendaTrabalho,
                TempoEmprego: fisica.TempoEmprego,
                TipoComprovanteRenda: fisica.TipoComprovanteRenda,
                OutrasInformacoes: fisica.OutrasInformacoes,
                TrabalhoOutrasInformacoes: fisica.TrabalhoOutrasInformacoes,
                EmpresaRua: fisica.EmpresaRua,
                EmpresaNumero: fisica.EmpresaNumero,
                EmpresaComplemento: fisica.EmpresaComplemento,
                EmpresaBairro: fisica.EmpresaBairro,
                EmpresaCidade: fisica.EmpresaCidade,
                EmpresaEstado: fisica.EmpresaEstado,
                EmpresaCep: FormatCepForDisplay(fisica.EmpresaCep),
                DadosBancarios: fisica.DadosBancarios,
                BancoCodigo: fisica.BancoCodigo,
                BancoNome: fisica.BancoNome,
                AgenciaNumero: fisica.AgenciaNumero,
                AgenciaDigito: fisica.AgenciaDigito,
                ContaNumero: fisica.ContaNumero,
                ContaDigito: fisica.ContaDigito,
                ContaTipo: fisica.ContaTipo,
                TitularNome: fisica.TitularNome,
                TitularDocumento: FormatCpfCnpjByLength(fisica.TitularDocumento),
                PixTipo: fisica.PixTipo,
                PixChave: FormatPixChaveForDisplay(fisica.PixChave, fisica.PixTipo),
                RepassePreferencial: fisica.RepassePreferencial,
                ConjugeNome: fisica.ConjugeNome,
                ConjugeRg: FormatRgForDisplay(fisica.ConjugeRg),
                ConjugeCpf: FormatCpf(fisica.ConjugeCpf),
                ConjugeEmail: fisica.ConjugeEmail,
                ConjugeDataNascimento: fisica.ConjugeDataNascimento,
                ConjugeProfissao: fisica.ConjugeProfissao,
                ConjugeNacionalidade: fisica.ConjugeNacionalidade,
                ConjugeTelefone: FormatPhoneForDisplay(fisica.ConjugeTelefone),
                ConjugeDadosBancarios: fisica.ConjugeDadosBancarios,
                ConjugeObservacoes: fisica.ConjugeObservacoes,
                ConjugeOutrasInformacoes: fisica.ConjugeOutrasInformacoes ?? fisica.ConjugeObservacoes,
                ConjugePossuiTrabalho: fisica.ConjugePossuiTrabalho,
                ConjugeNomeEmpresaTrabalho: fisica.ConjugeNomeEmpresaTrabalho,
                ConjugeCnpjEmpresaTrabalho: FormatCnpj(fisica.ConjugeCnpjEmpresaTrabalho),
                ConjugeTelefoneEmpresaTrabalho: FormatPhoneForDisplay(fisica.ConjugeTelefoneEmpresaTrabalho),
                ConjugeEmailEmpresaTrabalho: fisica.ConjugeEmailEmpresaTrabalho,
                ConjugeCargoTrabalho: fisica.ConjugeCargoTrabalho,
                ConjugeRendaTrabalho: fisica.ConjugeRendaTrabalho,
                ConjugeTempoEmprego: fisica.ConjugeTempoEmprego,
                ConjugeTipoComprovanteRenda: fisica.ConjugeTipoComprovanteRenda,
                ConjugeTrabalhoOutrasInformacoes: fisica.ConjugeTrabalhoOutrasInformacoes,
                ConjugeEmpresaRua: fisica.ConjugeEmpresaRua,
                ConjugeEmpresaNumero: fisica.ConjugeEmpresaNumero,
                ConjugeEmpresaComplemento: fisica.ConjugeEmpresaComplemento,
                ConjugeEmpresaBairro: fisica.ConjugeEmpresaBairro,
                ConjugeEmpresaCidade: fisica.ConjugeEmpresaCidade,
                ConjugeEmpresaEstado: fisica.ConjugeEmpresaEstado,
                ConjugeEmpresaCep: FormatCepForDisplay(fisica.ConjugeEmpresaCep));
        }

        var juridica = pessoa.PessoaJuridica;
        return new CreatePessoaRequest(
            TipoPessoa: pessoa.TipoPessoa,
            NomeDisplay: pessoa.NomeDisplay,
            Telefone: FormatPhoneForDisplay(pessoa.Telefone),
            Email: pessoa.Email,
            Documento: FormatCnpj(juridica?.Cnpj),
            Observacoes: pessoa.Observacoes,
            Rua: juridica?.EmpresaRua,
            Numero: juridica?.EmpresaNumero,
            Complemento: juridica?.EmpresaComplemento,
            Bairro: juridica?.EmpresaBairro,
            Cidade: juridica?.EmpresaCidade,
            Estado: juridica?.EmpresaEstado,
            Cep: FormatCepForDisplay(juridica?.EmpresaCep),
            NomeFantasia: juridica?.NomeFantasia,
            Atividade: juridica?.Atividade,
            ReceitaMensal: juridica?.ReceitaMensal,
            InscricaoEstadual: juridica?.InscricaoEstadual,
            InscricaoMunicipal: juridica?.InscricaoMunicipal,
            DataAbertura: juridica?.DataAbertura,
            ResponsavelNome: juridica?.ResponsavelNome,
            ResponsavelCargo: juridica?.ResponsavelCargo,
            ResponsavelEndereco: null,
            ResponsavelRua: juridica?.ResponsavelRua,
            ResponsavelNumero: juridica?.ResponsavelNumero,
            ResponsavelComplemento: juridica?.ResponsavelComplemento,
            ResponsavelBairro: juridica?.ResponsavelBairro,
            ResponsavelCidade: juridica?.ResponsavelCidade,
            ResponsavelEstado: juridica?.ResponsavelEstado,
            ResponsavelCep: FormatCepForDisplay(juridica?.ResponsavelCep),
            ResponsavelEstadoCivil: juridica?.ResponsavelEstadoCivil,
            ResponsavelNacionalidade: juridica?.ResponsavelNacionalidade,
            ResponsavelDataNascimento: juridica?.ResponsavelDataNascimento,
            ResponsavelTelefone: FormatPhoneForDisplay(juridica?.ResponsavelTelefone),
            ResponsavelEmail: juridica?.ResponsavelEmail,
            ResponsavelRg: FormatRgForDisplay(juridica?.ResponsavelRg),
            ResponsavelCpf: FormatCpf(juridica?.ResponsavelCpf),
            ResponsavelProfissao: juridica?.ResponsavelProfissao,
            ResponsavelOndeTrabalha: juridica?.ResponsavelOndeTrabalha,
            ResponsavelEnderecoTrabalho: juridica?.ResponsavelEnderecoTrabalho,
            ResponsavelNomeEmpresaTrabalho: juridica?.ResponsavelNomeEmpresaTrabalho,
            ResponsavelTelefoneEmpresaTrabalho: FormatPhoneForDisplay(juridica?.ResponsavelTelefoneEmpresaTrabalho),
            ResponsavelDadosBancarios: juridica?.ResponsavelDadosBancarios,
            ResponsavelBancoCodigo: juridica?.ResponsavelBancoCodigo,
            ResponsavelBancoNome: juridica?.ResponsavelBancoNome,
            ResponsavelAgenciaNumero: juridica?.ResponsavelAgenciaNumero,
            ResponsavelAgenciaDigito: juridica?.ResponsavelAgenciaDigito,
            ResponsavelContaNumero: juridica?.ResponsavelContaNumero,
            ResponsavelContaDigito: juridica?.ResponsavelContaDigito,
            ResponsavelContaTipo: juridica?.ResponsavelContaTipo,
            ResponsavelTitularNome: juridica?.ResponsavelTitularNome,
            ResponsavelTitularDocumento: FormatCpfCnpjByLength(juridica?.ResponsavelTitularDocumento),
            ResponsavelPixTipo: juridica?.ResponsavelPixTipo,
            ResponsavelPixChave: FormatPixChaveForDisplay(juridica?.ResponsavelPixChave, juridica?.ResponsavelPixTipo),
            ResponsavelRepassePreferencial: juridica?.ResponsavelRepassePreferencial,
            ResponsavelObservacoes: juridica?.ResponsavelObservacoes);
    }
}


