// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monthoya.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Monthoya.Data.Migrations
{
    [DbContext(typeof(MonthoyaDbContext))]
    [Migration("20260531045041_AddPessoaFisicaOtherInformationFields")]
    partial class AddPessoaFisicaOtherInformationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Monthoya.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Access")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedLoginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedLoginName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Boleto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BancoProvider")
                        .HasColumnType("text");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("ErroMensagem")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<Guid?>("LancamentoFinanceiroId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinhaDigitavel")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NossoNumero")
                        .HasColumnType("text");

                    b.Property<string>("PayloadRequest")
                        .HasColumnType("text");

                    b.Property<string>("PayloadResponse")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaPagadoraId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlPdf")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("boletos", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.CertificadoDigital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaJuridicaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("ValidadeFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidadeInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("certificados_digitais", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.ContaPagarReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Escopo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("contas_pagar_receber", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.DimobDeclaracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoCalendario")
                        .HasColumnType("integer");

                    b.Property<string>("ArquivoUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataGeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("dimob_declaracoes", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.DimobItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnoCalendario")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DimobDeclaracaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocatarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProprietarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorComissao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorImpostoRetido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorPagoProprietario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("dimob_itens", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.DocumentoGerado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConteudoFinal")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModeloId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("documentos_gerados", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.DocumentoModelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("ConteudoTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<int>("StatusRevisao")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("documentos_modelos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Ativo = true,
                            ConteudoTemplate = "Modelo inicial pendente de revisão jurídica do cliente.",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "Contrato residencial - modelo inicial",
                            StatusRevisao = 1,
                            Tipo = "contrato_residencial"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Ativo = true,
                            ConteudoTemplate = "Modelo inicial pendente de revisão.",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "Recibo do locatário - modelo inicial",
                            StatusRevisao = 1,
                            Tipo = "recibo_locatario"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Ativo = true,
                            ConteudoTemplate = "Estrutura inicial. Confirmar layout oficial vigente antes de exportar TXT.",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "DIMOB - relatório de conferência",
                            StatusRevisao = 0,
                            Tipo = "dimob"
                        });
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Imovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("CopelMatricula")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("Finalidade")
                        .HasColumnType("integer");

                    b.Property<string>("IptuMatricula")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("SaneparMatricula")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipoImovel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("ValorVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("imoveis", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.ImovelImagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId", "DisplayOrder");

                    b.ToTable("imovel_imagens", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.IndiceReajuste", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataReferencia")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("indices_reajuste", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            Codigo = "IGPM",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "IGP-M",
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            Codigo = "IPCA",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "IPCA",
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Ativo = true,
                            Codigo = "INPC",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "INPC",
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Ativo = true,
                            Codigo = "IVAR",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "IVAR",
                            Tipo = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Ativo = true,
                            Codigo = "CUSTOM",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Nome = "Custom/manual",
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("Monthoya.Core.Entities.LancamentoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataCompetencia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("lancamentos_financeiros", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Locacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AluguelAntecipado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataProximoReajuste")
                        .HasColumnType("date");

                    b.Property<bool>("DescontoAteVencimentoAtivo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("DescontoAteVencimentoPercentual")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("DescontoAteVencimentoValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("DiaBase")
                        .HasColumnType("integer");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IndiceReajusteId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("JurosPercentual")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<Guid>("LocatarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModeloTaxaAdministracao")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MultaPercentual")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int?>("PeriodoMeses")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProprietarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TaxaAdministracaoPercentual")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal?>("TaxaAdministracaoValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TaxaContratoValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("TaxaRenovacaoValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VencimentoLocatarioDia")
                        .HasColumnType("integer");

                    b.Property<int?>("VencimentoProprietarioDia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.HasIndex("IndiceReajusteId");

                    b.HasIndex("LocatarioId");

                    b.HasIndex("ProprietarioId");

                    b.ToTable("locacoes", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.LocacaoFiador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FiadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FiadorId");

                    b.HasIndex("LocacaoId", "FiadorId")
                        .IsUnique();

                    b.ToTable("locacao_fiadores", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.ManutencaoImovel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataExecucao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataSolicitacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("manutencoes_imovel", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Aliquota")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("CodigoVerificacao")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("ErroMensagem")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<decimal?>("IssValor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("LancamentoFinanceiroId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("PayloadRequest")
                        .HasColumnType("text");

                    b.Property<string>("PayloadResponse")
                        .HasColumnType("text");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("PessoaTomadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorServico")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("XmlConteudo")
                        .HasColumnType("text");

                    b.Property<string>("XmlUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("notas_fiscais", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NomeDisplay")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("pessoas", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataValidade")
                        .HasColumnType("date");

                    b.Property<string>("DocumentoDe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("pessoa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OcrCamposAplicados")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OcrErroMensagem")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("OcrProcessadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OcrStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OcrTextoExtraido")
                        .HasColumnType("text");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId", "Tipo");

                    b.ToTable("pessoa_documentos", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaFisica", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CargoTrabalho")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CnpjEmpresaTrabalho")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ConjugeCargoTrabalho")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ConjugeCnpjEmpresaTrabalho")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConjugeCpf")
                        .HasColumnType("text");

                    b.Property<string>("ConjugeDadosBancarios")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("ConjugeDataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("ConjugeEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ConjugeEmailEmpresaTrabalho")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ConjugeEmpresaBairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ConjugeEmpresaCep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConjugeEmpresaCidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ConjugeEmpresaComplemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ConjugeEmpresaEstado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ConjugeEmpresaNumero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ConjugeEmpresaRua")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("ConjugeNacionalidade")
                        .HasColumnType("text");

                    b.Property<string>("ConjugeNome")
                        .HasColumnType("text");

                    b.Property<string>("ConjugeNomeEmpresaTrabalho")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("ConjugeObservacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ConjugeOutrasInformacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool?>("ConjugePossuiTrabalho")
                        .HasColumnType("boolean");

                    b.Property<string>("ConjugeProfissao")
                        .HasColumnType("text");

                    b.Property<decimal?>("ConjugeRendaTrabalho")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ConjugeRg")
                        .HasColumnType("text");

                    b.Property<string>("ConjugeTelefone")
                        .HasColumnType("text");

                    b.Property<string>("ConjugeTelefoneEmpresaTrabalho")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConjugeTempoEmprego")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ConjugeTipoComprovanteRenda")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ConjugeTrabalhoOutrasInformacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DadosBancarios")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailEmpresaTrabalho")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmpresaBairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmpresaCep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmpresaCidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmpresaComplemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmpresaEstado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("EmpresaNumero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EmpresaRua")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("EnderecoTrabalho")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("NomeEmpresaTrabalho")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("OndeTrabalha")
                        .HasColumnType("text");

                    b.Property<string>("OutrasInformacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PetQual")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool?>("PossuiPet")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PossuiTrabalho")
                        .HasColumnType("boolean");

                    b.Property<string>("Profissao")
                        .HasColumnType("text");

                    b.Property<decimal?>("RendaTrabalho")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TelefoneEmpresaTrabalho")
                        .HasColumnType("text");

                    b.Property<string>("TempoEmprego")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipoComprovanteRenda")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("TrabalhoOutrasInformacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("PessoaId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL AND \"Cpf\" <> ''");

                    b.ToTable("pessoa_fisica", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaJuridica", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Atividade")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateOnly?>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<string>("EmpresaBairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmpresaCep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EmpresaCidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmpresaComplemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EmpresaEstado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("EmpresaNumero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EmpresaRua")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<decimal?>("ReceitaMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ResponsavelBairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ResponsavelCargo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ResponsavelCep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResponsavelCidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ResponsavelComplemento")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ResponsavelCpf")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelDadosBancarios")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ResponsavelDataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("ResponsavelEmail")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelEnderecoTrabalho")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelEstado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("ResponsavelEstadoCivil")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelNacionalidade")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelNome")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelNomeEmpresaTrabalho")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelNumero")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ResponsavelObservacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ResponsavelOndeTrabalha")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelProfissao")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelRg")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelRua")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("ResponsavelTelefone")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelTelefoneEmpresaTrabalho")
                        .HasColumnType("text");

                    b.HasKey("PessoaId");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"Cnpj\" IS NOT NULL AND \"Cnpj\" <> ''");

                    b.ToTable("pessoa_juridica", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId", "Role")
                        .IsUnique();

                    b.ToTable("pessoa_roles", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Rescisao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataRescisao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataSolicitacao")
                        .HasColumnType("date");

                    b.Property<decimal?>("DebitosTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VistoriaSaidaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("rescisoes", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Vistoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataVistoria")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("ImovelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("vistorias", (string)null);
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Imovel", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.ImovelImagem", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Imovel", "Imovel")
                        .WithMany("Imagens")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Locacao", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Monthoya.Core.Entities.IndiceReajuste", "IndiceReajuste")
                        .WithMany()
                        .HasForeignKey("IndiceReajusteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Locatario")
                        .WithMany()
                        .HasForeignKey("LocatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Imovel");

                    b.Navigation("IndiceReajuste");

                    b.Navigation("Locatario");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.LocacaoFiador", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Fiador")
                        .WithMany()
                        .HasForeignKey("FiadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Monthoya.Core.Entities.Locacao", "Locacao")
                        .WithMany("Fiadores")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fiador");

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaDocumento", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Pessoa")
                        .WithMany("Documentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaFisica", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Pessoa")
                        .WithOne("PessoaFisica")
                        .HasForeignKey("Monthoya.Core.Entities.PessoaFisica", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaJuridica", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Pessoa")
                        .WithOne("PessoaJuridica")
                        .HasForeignKey("Monthoya.Core.Entities.PessoaJuridica", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.PessoaRole", b =>
                {
                    b.HasOne("Monthoya.Core.Entities.Pessoa", "Pessoa")
                        .WithMany("Roles")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Imovel", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Locacao", b =>
                {
                    b.Navigation("Fiadores");
                });

            modelBuilder.Entity("Monthoya.Core.Entities.Pessoa", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("PessoaFisica");

                    b.Navigation("PessoaJuridica");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
