using Monthoya.Core.Entities;

namespace Monthoya.Desktop.Views;

public partial class ShellWindow
{
private sealed record ImoveisPageState(
        string SearchText,
        Guid? SelectedImovelId,
        Guid? ProprietarioId,
        ImovelFinalidade Finalidade,
        string Rua,
        string Numero,
        string Complemento,
        string Bairro,
        string Cidade,
        string Estado,
        string Cep,
        string TipoImovel,
        string Sanepar,
        string Copel,
    string IptuInscricaoImobiliaria,
    string IptuCadastroImovel,
        string ColetaLixo,
        string ValorAluguel,
        string ValorVenda,
        string ValorCondominio,
        string ValorIptu,
        string Latitude,
        string Longitude,
        ImovelStatus Status,
        string Quartos,
        string Suites,
        string Banheiros,
        string Vagas,
        string AreaConstruida,
        string AreaTerreno,
        bool? Mobiliado,
        bool? AceitaPets,
        string Descricao,
        string DescricaoPublica,
        string Observacoes,
        bool PublicarSite,
        bool PublicarApp,
        bool Destaque,
        bool MostrarEnderecoCompleto,
        ImovelEnderecoPublicoModo ModoEnderecoPublico,
        ImovelChavePosse ChavePosse,
        string ChaveCodigo,
        string ChaveQuemTem,
        string ChaveTelefone,
        string ChaveContatoNome,
        string ChaveContatoDocumento,
        string ChaveLocal,
        string ChaveHorario,
        bool ChaveAutorizacao,
        string ChaveObservacoes) : IShellPageState
    {
        public static ImoveisPageState Default { get; } = new(
            SearchText: "",
            SelectedImovelId: null,
            ProprietarioId: null,
            Finalidade: ImovelFinalidade.Locacao,
            Rua: "",
            Numero: "",
            Complemento: "",
            Bairro: "",
            Cidade: "ParanavaÃ­",
            Estado: "PR",
            Cep: "",
            TipoImovel: "",
            Sanepar: "",
            Copel: "",
            IptuInscricaoImobiliaria: "",
            IptuCadastroImovel: "",
            ColetaLixo: "",
            ValorAluguel: "",
            ValorVenda: "",
            ValorCondominio: "",
            ValorIptu: "",
            Latitude: "",
            Longitude: "",
            Status: ImovelStatus.Disponivel,
            Quartos: "",
            Suites: "",
            Banheiros: "",
            Vagas: "",
            AreaConstruida: "",
            AreaTerreno: "",
            Mobiliado: false,
            AceitaPets: false,
            Descricao: "",
            DescricaoPublica: "",
            Observacoes: "",
            PublicarSite: false,
            PublicarApp: false,
            Destaque: false,
            MostrarEnderecoCompleto: false,
            ModoEnderecoPublico: ImovelEnderecoPublicoModo.BairroCidade,
            ChavePosse: ImovelChavePosse.NaoCadastrada,
            ChaveCodigo: "",
            ChaveQuemTem: "",
            ChaveTelefone: "",
            ChaveContatoNome: "",
            ChaveContatoDocumento: "",
            ChaveLocal: "",
            ChaveHorario: "",
            ChaveAutorizacao: false,
            ChaveObservacoes: ""
        );
    }
}